users:
    path:     /
    defaults: { _controller: ApiBundle:Users:getUsers }
    methods:  [GET]

users_show:
    path:     /{id}
    defaults: { _controller: ApiBundle:Users:showUser }
    methods:  [GET]

users_update:
    path:     /{id}
    defaults: { _controller: ApiBundle:Users:updateUser }
    methods:  [PUT]

users_create:
    path:     /
    defaults: { _controller: ApiBundle:Users:createUser }
    methods:  [POST]
