services:
#    api.example:
#        class: Api\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api:
        class: Api\ApiBundle\Services\Api
        arguments: ["@doctrine.orm.entity_manager", "@service_container" ]